name: i18n - Upload Docs
on:
  workflow_dispatch:
  schedule:
    # runs every weekday at 11:00 AM UTC
    - cron: '0 11 * * 1-5'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}
  CROWDIN_API_URL: 'https://freecodecamp.crowdin.com/api/v2/'
  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_DOCS }}

jobs:
  i18n-upload-docs-files:
    name: Docs
    runs-on: ubuntu-22.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout Source Files
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Generate Crowdin Config
        uses: freecodecamp/crowdin-action@4e2409afb137b2e55cc91a7bc111afdce781a817 # main
        env:
          PLUGIN: 'generate-config'
          PROJECT_NAME: 'docs'

      - name: Crowdin Upload
        uses: crowdin/github-action@c953b17499daa6be3e5afbf7a63616fb02d8b18d # master
        # options: https://github.com/crowdin/github-action/blob/master/action.yml
        with:
          # uploads
          upload_sources: true
          upload_translations: false
          auto_approve_imported: false
          import_eq_suggestions: false

          # downloads
          download_translations: false

          # pull-request
          create_pull_request: false

          # global options
          config: './crowdin-config.yml'
          base_url: ${{ secrets.CROWDIN_BASE_URL_FCC }}

          # Uncomment below to debug
          # dryrun_action: true
